spring.application.name=deploy

spring.datasource.url=${DB_URL: jdbc:postgresql://pg-deploy1-akuhal065-b9b8.g.aivencloud.com:23024/defaultdb?sslmode=require}
spring.datasource.username=${DB_USERNAME: avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_×UL_wvDTPzLDZtWNS9h}
spring.datasource.driver-class-name=org.postgresql.Driver

